version: '3'

services:
  web:
    depends_on: []
    build:
      context: ./csp-main
      dockerfile: Dockerfile
    environment: 
      - PORT=8100
      - USE_REPORTER=1
    volumes:
      - ./csp-main:/var/www/html/
      - ./_shared:/data/logs/
    ports:
      - "8100:8100"