version: '3'

services:
  web:
    depends_on: 
      - csp-ws
    build:
      context: ./csp-main
      dockerfile: Dockerfile
    environment: 
      - PORT=8100
      - REPORTER_WS=localhost:8110
    volumes:
      - ./csp-main:/var/www/html/
      - ./_shared:/data/logs/
    ports:
      - "8100:8100"
  
  csp-ws:
    build:
      context: ./csp-ws/
      dockerfile: ./Dockerfile
    volumes:
      - ./_shared:/data/logs/
    environment: 
      - PORT=8110
    working_dir: /var/www/html/
    ports:
      - "8110:8110"
