version: '3'

services:
  web:
    depends_on: 
      - ws
    build:
      context: . 
      dockerfile: Dockerfile.web
    environment: 
      - REPORTER_WS=localhost:8110
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    command: cat /etc/apache2/apache2.conf
  
  ws:
    build:
      context: . 
      dockerfile: Dockerfile.ws

    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command: bash -c "( [ ! -d ./vendor ] && composer install ); php ws.php"
    ports:
      - "8110:8110"
